#
# Generated by Ansible
#
ui = false
listener "tcp" {
  tls_disable = 0
  address = "10.0.0.1:8200"
  tls_min_version = "tls1.2"
  tls_cipher_suites = "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
}
storage "raft" {
  path = "/data/vault"
  test = 425
  node_id = "node1"
  retry_join_max = 3
}
listener "tcp" {
  address = "10.0.0.2:8200"
  tls_disable = 1
}
api_addr = "https://vault.example.com"
cluster_port = 8201
telemetry "statsd" {
  address = "127.0.0.1:8125"
}
