---
- name: Prepare targets
  hosts: all
  gather_facts: false
  tasks:
    - name: Wait for container to be ready
      ansible.builtin.raw: systemctl is-active basic.target
      register: _wait_result
      until: _wait_result.rc == 0
      retries: 33
      delay: 1
      changed_when: false
    - name: Install requirements
      ansible.builtin.apt:
        name: unzip
        update_cache: true
        install_recommends: false
      poll: 5
      async: 77
      register: _temp_result
      until: _temp_result is succeeded
      timeout: 333
      retries: 5
      delay: 1
